-- BoardReady PostgreSQL schema mapping — Phase 3 (design + test-on-copy only).
-- Generated from a line-by-line mapping of /home/claude/backend/db.js's live
-- SQLite schema (the CREATE TABLE block plus every additive ALTER TABLE and
-- the two CHECK-constraint table-rebuild blocks, all folded into one final
-- shape here — this is the END STATE the live schema reaches today, not a
-- step-by-step replay of every ALTER).
--
-- MAPPING RULES APPLIED THROUGHOUT:
--   INTEGER PRIMARY KEY AUTOINCREMENT  -> INTEGER GENERATED BY DEFAULT AS IDENTITY
--       ("BY DEFAULT", not "ALWAYS" — this lets the migration script insert
--       explicit ids copied from SQLite's own row ids, preserving every
--       foreign key relationship exactly; the identity sequence is then
--       fast-forwarded with setval() after data load so future inserts from
--       the running app continue the same numbering with no collision risk.)
--   TEXT ... CHECK(col IN (...))       -> TEXT ... CHECK(col IN (...))  (unchanged)
--       Deliberately NOT converted to a native Postgres ENUM type. content-
--       rules.js's provenance ladder has already grown twice in this
--       project's history (db.js's own two CHECK-widening table-rebuild
--       blocks, needed only because SQLite can't ALTER a CHECK in place) —
--       Postgres CAN alter a CHECK constraint directly (ALTER TABLE ... DROP
--       CONSTRAINT ... ADD CONSTRAINT ...), so keeping TEXT+CHECK preserves
--       that same "add a new allowed value later" flexibility with a SIMPLER
--       migration path than a native ENUM (which needs ALTER TYPE ... ADD
--       VALUE, cannot run inside the same transaction as other DDL before
--       PG12, and cannot remove values at all).
--   TEXT NOT NULL DEFAULT (datetime('now'))  -> TIMESTAMPTZ NOT NULL DEFAULT now()
--       See phase-3-migration-design-report.md, section "Timestamp handling"
--       for why TIMESTAMPTZ was chosen over keeping TEXT, and the exact
--       application-code call sites that must change at cutover time
--       (Phase 4) as a consequence — NOT changed in this phase.
--   *_json TEXT columns (options_json, parts_json, answers_json,
--   draft_answers_json, locked_answers_json, details_json)  -> kept as TEXT
--       Every one of these is read with JSON.parse()/written with
--       JSON.stringify() in application code and NEVER queried by SQL today
--       (no json_extract() call anywhere in the codebase) — converting to
--       JSONB would be a safe, purely-additive future enhancement, but is
--       NOT required for behavioral parity, so it is deliberately deferred
--       to avoid changing more than necessary in one migration.
--   Foreign keys                      -> unchanged, with ONE exception (next).
--   CIRCULAR FOREIGN KEY FINDING (tests <-> attempts):
--       tests.improves_attempt_id references attempts(id), while every
--       attempts row references tests(id) via attempts.test_id NOT NULL.
--       SQLite never surfaced this as a problem because it checks foreign
--       keys per-statement, not per-table, so the two tables can simply be
--       created in either order. Postgres validates a REFERENCES clause at
--       CREATE TABLE time, so the tables cannot be created in a strict
--       dependency order — one of the two FKs must be added after both
--       tables exist, OR marked DEFERRABLE. This schema uses DEFERRABLE
--       INITIALLY DEFERRED on tests.improves_attempt_id specifically so a
--       single bulk-load transaction (see migrate.js) can insert both tables
--       in one pass with `SET CONSTRAINTS ALL DEFERRED` and have every FK
--       checked once, correctly, at COMMIT — never a two-pass load.

BEGIN;

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('student','teacher')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE subjects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board TEXT NOT NULL CHECK (board IN ('CBSE','ICSE')),
  name TEXT NOT NULL,
  class TEXT NOT NULL DEFAULT '10',
  UNIQUE (board, name, class)
);

CREATE TABLE chapters (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id INTEGER NOT NULL REFERENCES subjects(id),
  name TEXT NOT NULL,
  order_index INTEGER NOT NULL DEFAULT 0
);

-- source_files BEFORE source_documents/questions: both reference it.
CREATE TABLE source_files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stable_id TEXT NOT NULL UNIQUE,
  original_filename TEXT NOT NULL,
  upload_ref TEXT,
  board TEXT,
  subject_name TEXT,
  class TEXT,
  source_section TEXT,
  sha256 TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  archive_path TEXT NOT NULL,
  uploaded_at TEXT,
  archived_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  notes TEXT
);

CREATE TABLE source_documents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  board TEXT,
  subject_name TEXT,
  chapter_name TEXT,
  ingested_count INTEGER NOT NULL DEFAULT 0,
  skipped_exact_duplicates INTEGER NOT NULL DEFAULT 0,
  flagged_near_duplicates INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'verified',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE source_document_files (
  source_document_id INTEGER NOT NULL REFERENCES source_documents(id),
  source_file_id INTEGER NOT NULL REFERENCES source_files(id),
  PRIMARY KEY (source_document_id, source_file_id)
);

CREATE TABLE questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_uid TEXT UNIQUE,
  chapter_id INTEGER NOT NULL REFERENCES chapters(id),
  kind TEXT NOT NULL CHECK (kind IN ('mcq','case','open')) DEFAULT 'mcq',
  sub_concept TEXT,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('Easy','Medium','Hard')) DEFAULT 'Medium',
  status TEXT NOT NULL CHECK (status IN ('draft','transcribed','needs_review','verified','qa_passed','published')) DEFAULT 'draft',
  marks INTEGER NOT NULL DEFAULT 1,
  text TEXT NOT NULL,
  normalized_text TEXT,
  options_json TEXT,
  correct INTEGER,
  parts_json TEXT,
  explanation TEXT,
  source TEXT,
  source_page TEXT,
  source_question_number TEXT,
  answer_key_ref TEXT,
  question_type TEXT,
  source_section TEXT,
  question_format TEXT,
  answer_status TEXT NOT NULL DEFAULT 'source_provided' CHECK (answer_status IN ('source_provided','unavailable','needs_review','verified')),
  source_document_id INTEGER REFERENCES source_documents(id),
  diagram_status TEXT NOT NULL DEFAULT 'needs_visual_review' CHECK (diagram_status IN ('not_applicable','source_diagram_preserved','needs_visual_review','ai_generated_pending')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- diagram_status was added in SQLite with no CHECK constraint (enforced only
-- in ingest.js). Adding the CHECK here is a deliberate, low-risk TIGHTENING
-- — see phase-3-migration-design-report.md's validation section, which
-- confirms every live row's value is already one of these four before this
-- constraint is relied upon.

CREATE TABLE visual_assets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id INTEGER NOT NULL REFERENCES questions(id),
  source_file_id INTEGER REFERENCES source_files(id),
  asset_type TEXT NOT NULL DEFAULT 'source_page_full' CHECK (asset_type IN ('source_page_full','source_cropped','ai_generated')),
  figure_label TEXT,
  asset_path TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE duplicate_flags (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  new_question_uid TEXT NOT NULL,
  existing_question_id INTEGER NOT NULL REFERENCES questions(id),
  similarity REAL NOT NULL,
  new_text TEXT NOT NULL,
  existing_text TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','kept_both','merged','discarded_new')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- attempts is created BEFORE tests, deliberately, and WITHOUT its test_id
-- foreign key inline — see the circular-FK finding at the top of this file.
-- Postgres requires a REFERENCES target to already exist at CREATE TABLE
-- time (even for a deferrable constraint), so the two halves of this real
-- cycle (attempts.test_id -> tests, tests.improves_attempt_id -> attempts)
-- cannot both be declared inline no matter which table is written first.
-- attempts.test_id's FK is added via ALTER TABLE once `tests` exists, a few
-- statements down.
CREATE TABLE attempts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id INTEGER NOT NULL,
  student_id INTEGER NOT NULL REFERENCES users(id),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  submitted_at TIMESTAMPTZ,
  score REAL,
  max_score REAL,
  time_exceeded_seconds INTEGER,
  answers_json TEXT,
  draft_answers_json TEXT,
  draft_saved_at TIMESTAMPTZ,
  locked_answers_json TEXT
);

CREATE TABLE tests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES users(id),
  subject_id INTEGER NOT NULL REFERENCES subjects(id),
  kind TEXT NOT NULL CHECK (kind IN ('practice','full','challenge')) DEFAULT 'practice',
  practice_chapter_id INTEGER REFERENCES chapters(id),
  practice_sub_concept TEXT,
  duration_seconds INTEGER NOT NULL DEFAULT 1200,
  improves_attempt_id INTEGER REFERENCES attempts(id) DEFERRABLE INITIALLY DEFERRED,
  feedback_mode TEXT NOT NULL DEFAULT 'immediate',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The other half of the cycle, added now that `tests` exists. Also marked
-- DEFERRABLE (belt-and-braces): the bulk loader wraps the whole load in one
-- transaction with SET CONSTRAINTS ALL DEFERRED regardless of per-table load
-- order, so neither direction of this cycle can fail mid-transaction no
-- matter which table's rows happen to be inserted first.
ALTER TABLE attempts ADD CONSTRAINT attempts_test_id_fkey
  FOREIGN KEY (test_id) REFERENCES tests(id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE test_questions (
  test_id INTEGER NOT NULL REFERENCES tests(id),
  question_id INTEGER NOT NULL REFERENCES questions(id),
  order_index INTEGER NOT NULL,
  PRIMARY KEY (test_id, question_id)
);

CREATE TABLE subscriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES users(id),
  plan TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('active','expired','cancelled')) DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  entity_type TEXT,
  entity_id INTEGER,
  student_id INTEGER,
  details_json TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMIT;
